# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Search Indexer

on:
  push:
    branches: [ "main" ]
    paths:
    - 'FinLegal.Search/**'
    - 'FinLegal.Hosting/**'
    - 'FinLegal.Search.Shared/**'
    - 'FinLegal.Search.Indexer/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build "FinLegal.Search.Indexer\FinLegal.Search.Indexer.csproj"
    - name: Test
      run: dotnet test --no-build --verbosity normal
