name: SDK CD Pipeline
on: workflow_dispatch

jobs:
    build-main:
        env:
          GIT_TAG: ${{ inputs.ENV }}
        name: Build Sdk
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.semver-outputs.outputs.version }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
                  
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0"

            - name: Build
              working-directory: FinLegal.Search
              run: dotnet build --configuration Release /p:Version=${{ env.GIT_TAG }}
            
