name: SDK CD Pipeline
on: workflow_dispatch

jobs:
    build-main:
        env:
          GIT_TAG: ${{ inputs.ENV }}
        name: Build Sdk
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.semver-outputs.outputs.version }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                  
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0"

            - name: Build
              working-directory: FinLegal.Search
              run: dotnet pack --output ./build --configuration Release /p:Version=${{ env.GIT_TAG }}
              
            - name: Upload SDK Artifact
              uses: actions/upload-artifact@v4
              with:
                name: sdk-build-output
                path: ./src/build
            
