name: Nuget schnizz
on: workflow_dispatch

jobs:
    build-main:
        name: Build Sdk
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0                  
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0"
            - name: Build
              working-directory: FinLegal.Search
              run: dotnet pack --output ./publish --configuration Release             
            - name: Upload SDK Artifact
              uses: actions/upload-artifact@v4
              with:
                name: sdk-build-output
                path: ./FinLegal.Search/publish                
            - name: NuGet Push
              run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/simonleewaters/index.json"
