name: SDK CD Pipeline
on: workflow_dispatch

jobs:
    build-main:
        name: Build Sdk
        runs-on: ubuntu-latest
        outputs:
          version: ${{ steps.semver-outputs.outputs.version }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
                  
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0"
                  
            - name: Get Next Semantic Version
              id: semver
              uses: ietf-tools/semver-action@v1
              with:
                  token: ${{ github.token }}
                  branch: main
                  patchList: fix, bugfix, perf, refactor, test, tests, chore
                  noVersionBumpBehavior: current
            
            - name: Output SemVer 
              id: semver-outputs
              run: echo "VERSION=${{ steps.semver.outputs.nextStrict }}" >> $GITHUB_OUTPUT
            
            - name: Restore Dependencies
              working-directory: src
              run: dotnet restore CaseDefinitionService.Sdk/CaseDefinitionService.Sdk.csproj

            - name: Build Nuget Package
              working-directory: FinLegal.Search
              run: dotnet pack --output ./build --configuration Release /p:Version=${{ steps.semver.outputs.nextStrict }}
              
            - name: Upload SDK Artifact
              uses: actions/upload-artifact@v4
              with:
                name: sdk-build-output
                path: ./src/build
